strings:
	twine generate-all strings/twine.txt \
		--output-path . \
		--format android \
		--output-dir androidApp/src/main/res
	twine generate-all strings/twine.txt \
		--output-path . \
		--format apple \
		--output-dir iosApp/eSklepios
