build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    threshold: 420
  CyclomaticComplexMethod:
    threshold: 30
  LongParameterList:
    functionThreshold: 11
    constructorThreshold: 8
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInObjects: 20
    thresholdInInterfaces: 20
    thresholdInFiles: 14

naming:
  FunctionNaming:
    excludes: ['**/test/**', '**/commonTest/**', '**/androidTest/**']
    ignoreAnnotated: ['Composable']
  PackageNaming:
    packagePattern: '[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*'
  TopLevelPropertyNaming:
    active: true

style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 4
  MaxLineLength:
    maxLineLength: 140
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignore|expected|Preview|.*Preview)'
  WildcardImport:
    excludeImports:
      - 'androidx.compose.*'
      - 'androidx.compose.material.icons.*'
      - 'androidx.compose.animation.core.*'
      - 'lu.esklepios.app.core.ui.*'
      - 'io.mockk.*'
      - 'kotlinx.coroutines.test.*'
      - 'lu.esklepios.app.domain.model.*'
      - 'lu.esklepios.app.domain.usecase.*'
      - 'org.junit.*'
      - 'androidx.navigation.compose.*'

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Exception
    allowedExceptionNameRegex: '_|(ignore|expected).*'
    excludes: ['**/test/**', '**/commonTest/**']

potential-bugs:
  LateinitUsage:
    active: false
