build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInObjects: 20
    thresholdInInterfaces: 20

naming:
  FunctionNaming:
    excludes: ['**/test/**', '**/commonTest/**', '**/androidTest/**']
  TopLevelPropertyNaming:
    active: true

style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 4
  MaxLineLength:
    maxLineLength: 140
  UnusedPrivateMember:
    active: true

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Exception
    allowedExceptionNameRegex: '_|(ignore|expected).*'
    excludes: ['**/test/**', '**/commonTest/**']

potential-bugs:
  LateinitUsage:
    active: false
